config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]

  def index
    @tasks=Task.all
  end

  def new
    @task=Task.new
  end

  def create
    @task=Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      render 'new' ,status: :unprocessable_entity#(バリデーションエラー時に返すステータスコード（４２２）にレンダリングする)
    end
  end

  def edit
    # @task=Task.find(params[:id])
  end

  def update
    # @task=Task.find(params[:id])
    if @task.update(task_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    # @task=Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private
  def task_params
    params.require(:task).permit(:title)
  end

  def set_task
    @task=Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>
  <%= form_with model: @task, url: task_path(@task), method: :patch do |f| %>
    <p>
      <%= f.label :title %></br>
      <%= f.text_field :title %>
      <% if @task.errors.any? %>
        <%= @task.errors.messages[:title][0] %>
        <%#= @task.errors.count %>
          <%# @task.erros.full_message.each do |message| %>
            <%#= message %>
          <%# end %>
      <% end %>
    </p>
    <p>
      <%= f.submit "編集内容を保存" %>
    </p>
  <% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= link_to "新規作成", new_task_path %>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= check_box_tag '', '' %>
      <%= task.title %>
      <%= link_to "[編集]", edit_task_path(task) %>
      <%= link_to "[削除]", task_path(task), method: :delete,
      # 下の行は、rails7で使用可能。javascriptのような確認ダイヤルをさせることができる
      data: {turbo_method: 'delete', turbo_confirm: 'Are you sure?'} %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New</h1>
  <%= form_with model: @task, url: tasks_path, method: :post do |f| %>
    <p>
      <%= f.label :title %></br>
      <%= f.text_field :title %>
      <% if @task.errors.any? %>
        <%= @task.errors.messages[:title][0] %>
        <%#= @task.errors.count %>
          <%# @task.erros.full_message.each do |message| %>
            <%#= message %>
          <%# end %>
      <% end %>
    </p>
    <p>
      <%= f.submit "新規作成" %>
    </p>
  <% end %>